from .lms_vision import NODE_CLASS_MAPPINGS as LMS_NODE_CLASS_MAPPINGS
from .lms_vision import NODE_DISPLAY_NAME_MAPPINGS as LMS_NODE_DISPLAY_NAME_MAPPINGS

from .batch_nodes import NODE_CLASS_MAPPINGS as BATCH_NODE_CLASS_MAPPINGS
from .batch_nodes import NODE_DISPLAY_NAME_MAPPINGS as BATCH_NODE_DISPLAY_NAME_MAPPINGS

# 合并字典
NODE_CLASS_MAPPINGS = {**LMS_NODE_CLASS_MAPPINGS, **BATCH_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**LMS_NODE_DISPLAY_NAME_MAPPINGS, **BATCH_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']